name: Deploy

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev
    types: [opened, synchronize, reopened]

jobs:
  deploy:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        node: [20.x]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version: ${{matrix.node}}

      - name: Set up pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install

      - name: Lint
        run: pnpm lint

      - name: Migrations
        env:
          NEON_DB_URL: ${{secrets.DATABASE_URL}}
        run: pnpm generate:migrate

      - name: push Migrations
        env:
          NEON_DB_URL: ${{secrets.DATABASE_URL}}
        run: pnpm push
